### ISSUE TITLE
Undefined error

### ISSUE THREAD

**Issue by schilippe** [tristen/tablesort#59] opened 2015-01-19 04:23 UTC
I am getting "Uncaught TypeError: Cannot read property 'trim' of undefined" in tablesort.min.js:5 when trying to sort and empty table by clicking on the column header.

**Comment by ryanmjacobs** [comment] 2015-01-19 04:26
@schilippe Can you try using `tablesort.js` so we can pinpoint the right line number?

**Comment by ryanmjacobs** [comment] 2015-01-19 04:40
Nevermind, I reproduced it. It's on [line 84](https://github.com/tristen/tablesort/blob/gh-pages/src/tablesort.js#L84).

**Comment by schilippe** [comment] 2015-01-19 05:36
I tried fixing it with "if (item)" but then it gave an error with "match" on line 239

**Comment by ryanmjacobs** [comment] 2015-01-19 23:14
@schilippe I just pushed a fix. Can you try using this [tablesort.js](https://github.com/ryanmjacobs/tablesort/blob/empty-row-bug/src/tablesort.js) to confirm that it fixes it? Thanks.

**Comment by schilippe** [comment] 2015-01-20 18:39
I tried it, it doesn't give the error anymore but it messes with the styling of my table now when the table is empty. In particular, it makes the first empty row larger than the table header.

**Comment by schilippe** [comment] 2015-01-20 18:45
Ok, I see what you did. You made sure there are as many columns as the header. But in my implementation an empty table has just one row with one column below the header so that's why your fix messes with it. Why would you need there to be as many columns as the header? That is an unnecessary constraint.

**Comment by ryanmjacobs** [comment] 2015-01-23 04:54
Sorry for the late-ish reply.

Ensuring that each row had the same amount of cells as the header did two things. First of all, it squelched  the errors from passing in undefined `<td>` elements. And second of all, it allowed the elements to be sorted &mdash; numerically they would be rendered as equivalent to 0 (or the least possible value for whatever type it was).

But you're right, it is an unnecessary constraint. It would be better to check if `<td> === undefined`, then do some processing afterwards.

I'll try to come up with an elegant solution this weekend. If anyone else has a good approach to this problem, please speak up :grinning:

**Comment by xPaw** [comment] 2015-02-19 15:37
I am unable to reproduce this issue on master, it simply doesn't try to sort when tbody is empty.

**Comment by xPaw** [comment] 2015-02-23 09:14
@schilippe Try again with v3.0.0.

**Comment by tristen** [comment] 2015-03-11 20:14
Closing here. @schilippe feel free to re-open if the issue persists.

**Closed by tristen** 2015-03-11 20:14 UTC
Labels: bug
