### ISSUE TITLE
data-sort-method='none' still does not work.

### ISSUE THREAD

**Issue by savisky** [tristen/tablesort#192] opened 2020-06-02 08:56 UTC
data-sort-method='none' still does not work.
The previous topic found a fix and that code added to line 113. By default its there.
https://github.com/tristen/tablesort/blob/gh-pages/src/tablesort.js#L113

But it still does not work. Any ideas?

Thanks

**Comment by savisky** [comment] 2020-06-02 10:31
So I was able to fix it this way. Not sure if that the best way to do it.
CSS:
 .no-arrow {cursor:default !important; }
 .no-arrow:not(.no-sort):hover:after {  visibility: hidden !important;  }

HTML:
<th data-sort-method='none'  scope="col" class="no-arrow">Store</th>

Live demo:
https://www.perfumetr.com/perfume/1-million/

**Comment by tripu** [comment] 2020-06-02 10:38
Thank for reporting, and for those tests!

Isn't this a duplicate of #137? Please see the comment I just added over there, https://github.com/tristen/tablesort/issues/137#issuecomment-637450512.

**Closed** 2020-06-02 12:48 UTC
