### ISSUE TITLE
How do you use the provided sorts with browserify?

### ISSUE THREAD

**Issue by euoia** [tristen/tablesort#144] opened 2017-10-03 22:48 UTC
The README says to use the following with browserify:
```
// npm install tablesort
var tablesort = require('tablesort');

tablesort(el, options);
```

But what if I want to use (for example) `tablesort.number.js`? I couldn't find an easy way to use this from browserify, so I ended up copying the `tablesort.number.js` code.

Thanks for an excellent library.

**Comment by tristen** [comment] 2017-12-02 15:44
See dupe of https://github.com/tristen/tablesort/issues/94

**Closed by tristen** 2017-12-02 15:44 UTC
